server:
  port: 8085
  servlet:
    context-path: /
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dragon.entity
  configuration:
    map-underscore-to-camel-case: true
#mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimeZone=UTC
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource